config/routes.rb
Rails.application.routes.draw do
  resources :park

  #get '/123', to: 'parks#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/park_controller.rb
class ParkController < ApplicationController
  def index
    @park = Park.all
  end

  def new
    calc
  end



  private
    def park_params
      params.permit(:vehicle_type, :parking_hour)
    end

    # 停車場的收費方式為：
    # 機車：不計時數，每天 20 元
    # 汽車：前 2 個小時，每小時 40 元；超過 2 小時之後每小時 30 元。未滿一小時以一小時計費。停車費每天最高上限為 500 元。
    def calc
      @fee = 0
      parking_hour = park_params[:parking_hour].to_f.ceil

      return if park_params[:vehicle_type].blank?
      case park_params[:vehicle_type].to_sym
      when :motocycle
        @fee = 20 
      when :car
        if parking_hour <= 2
          @fee = parking_hour * 40
        else parking_hour > 2
          @fee = 80 + (parking_hour - 2) * 30
        end

        if @fee >= 500
          @fee = 500
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/park_helper.rb
module ParkHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingFee</title>
    <%= csrf_meta_tags %> <%= stylesheet_link_tag 'application', media: 'all',
    'data-turbolinks-track': 'reload' %> <%= javascript_pack_tag 'application',
    'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container"><%= yield %></div>
  </body>
</html>

app/views/park/edit.html.erb
<h1>汽車(car)停車費用查詢</h1>

app/views/park/index.html.erb
<h1>停車場</h1>

<h3>停車場收費標準</h3>
<table class="table">
  <thead>
    <tr>
      <td>車輛類型</td>
      <td>收費標準</td>
      <td>其他收費說明</td>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>motocycle</td>
      <td>$20/1天</td>
      <td>無</td>
    </tr>

    <tr>
      <td>car</td>
      <td>前 2 個小時，$40/1小時；超過 2 小時之後$30/1小時。</td>
      <td>未滿1小時以1小時計費。每天最高上限為 500 元。</td>
    </tr>

    <tr>
      <td></td>
      <td></td>
      <td>
        <%= link_to "試算總停車費用", new_park_path, class:"btn btn-danger
        btn-m" %>
      </td>
    </tr>
  </tbody>
</table>

app/views/park/new.html.erb
<h1>停車場</h1>

<h3>停車費試算</h3>
<table class="table">
  <thead>
    <tr>
      <td>車輛類型</td>
      <td>停車時數</td>
      <td>試算查詢</td>
      <td>總收費金額</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <select name="city_id" id="city_id">
          <option value="1">Motocycle</option>
          <option value="2">Car</option>
        </select>
      </td>

      <td>
        <select name="city_id" id="city_id">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
          <option value="9">9</option>
          <option value="10">10</option>
          <option value="11">11</option>
          <option value="12">12</option>
          <option value="13">13</option>
          <option value="14">14</option>
          <option value="15">15</option>
          <option value="16">16</option>
          <option value="17">17</option>
          <option value="18">18</option>
          <option value="19">19</option>
          <option value="20">20</option>
          <option value="21">21</option>
          <option value="22">22</option>
          <option value="23">23</option>
          <option value="24">24</option>
        </select>
      </td>

      <td><button class='btn'>查詢</button></td>

      <td><%= @fee %>元</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>
        <%= link_to "停車場收費標準", park_index_path, class:"btn btn-danger
        btn-m" %>
      </td>
    </tr>
  </tbody>
</table>